### ISSUE TITLE
State option appear while choosing the country with no state

### ISSUE THREAD

**Issue by Fayeakuzzamantonmoy** [getdokan/dokan#1709]
**Describe the bug**
The state is required in the vendor dashboard while vendors choose the United Kingdom as a country. Hence the United Kingdom has no state available.

**To Reproduce**

1. Go to the vendor dashboard
2. Click on Settings.
3. Under the settings of Store select the United Kingdom as a country
4. Try to save the changes without adding State. The State field is showing as required.

**Expected behavior**
While you put the United Kingdom as a country the state option shouldn't appear on the Store settings page

**Screenshots**
Please check it from here: https://prnt.sc/BjQNXZT54-DC

**Comment by jamil-mahmud** [comment]
Based on the [Discussion](https://github.com/getdokan/dokan/discussions/2549) reopening the issue for investigation. @Aunshon vai, can you kindly check it by taking this in work pipeline!?!

**Comment by jamil-mahmud** [comment]
@Fayeakuzzamantonmoy vai, the issue is reopened and kindly track this for the fix. While it will be fixed and checked kindly close the discussion as well

**Comment by jamil-mahmud** [comment]
@Fayeakuzzamantonmoy vai,
Is this issue solved by the merged PRs?

**Comment by Fayeakuzzamantonmoy** [comment]
@jamil-mahmud Bhai, the issue is still occurring on our local setup. Additionally, one of our clients has also reported the same issue on our WordPress.org support forum.

**Comment by jamil-mahmud** [comment]
> [@jamil-mahmud](https://github.com/jamil-mahmud) Bhai, the issue is still occurring on our local setup. Additionally, one of our clients has also reported the same issue on our WordPress.org support forum.

@Aunshon vai, can you kindly check into this according to this reply also kindly collaborate on this with @Fayeakuzzamantonmoy vai if needed

**Comment by jamil-mahmud** [comment]
@Fayeakuzzamantonmoy vai,

Currently the Save option right below state works properly. In the bottom, upgrade option we will do the enhancement but it would take some time so I will suggest that kindly let the client proceed with the save option right below state. Once it is updated according to feature scope @Aunshon vai will give an update here

**Comment by Fayeakuzzamantonmoy** [comment]
@Aunshon Bhai, it looks like the issue has now been resolved with the Setup Wizard.
