### ISSUE TITLE
BUG Dokan Quantity Discount option - Admin receive 0 commission if vendor use this feature

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2020]
### Bug Description

If vendors use the Quantity Discount option on a "Variable" Product, the admin receives 0 euro of commission and there is a bug as the vendor earning amount is bigger than the order amount making this Dokan quantity function unusable on the marketplace without losing money... Please review this video: https://share.vidyard.com/watch/3zPrfAhqdaHxvB9JfxxgiH?

And here list of improvment needed as for now this feature is not ready to be use: https://github.com/getdokan/dokan/issues/2019

### Step To Reproduce

Add a dokan quantity discount option to a product, buy it, and see yourself. https://share.vidyard.com/watch/3zPrfAhqdaHxvB9JfxxgiH?

### Expected Behaviour

That it works properly without admin losing money.

### Actual Behaviour

Admin does not get any commission and anaylytics are wrong: https://share.vidyard.com/watch/3zPrfAhqdaHxvB9JfxxgiH?

### Environment (please complete the following information)

```shell
1. Dokan Version: [latest]
2. Dokan Pro Version: [latest]
3. WooCommerce Version: [latest]
4. Browser [all]
5. Current Theme: [whatever the temmplate]
```

**Comment by Aunshon** [comment]
Hi @Sophie-2e,

We are pleased to inform you that we've addressed the issue you reported. In our next release, when you update Dokan, the solution will be included. 

For orders with variable products that have quantity discounts, the commission calculations will work as expected. 

Additionally, you'll find a new setting named "Regenerate order commission" on the Dokan Tools page. Be sure to click on this button for your previous orders. It will resolve commission-related issues for those orders.

However, if you encounter any further commission-related issues after these updates, please don't hesitate to reach out to our support team and make a client issue. We'll be more than happy to debug and resolve any lingering issues on your website.

Thank you for your patience and understanding. We're here to ensure everything runs smoothly.

**Comment by Sophie-2e** [comment]
Updated to Dokan 3.9, create a new order with a dokan discount, and I can confirm that the admin still receives 0 commission if there is a Dokan quantity discount in the order so the Dokan Quantity Discount Module is still not usable as admin don't earn any money, or even lost money if they paid payment gateway commission and shipping.

So bug not fixed.

**Comment by Sophie-2e** [comment]
Additionally, there is no new setting named "Regenerate order commission" on the Dokan Tools page with Dokan 3.9: https://ibb.co/k0wGqnv

**Comment by Aunshon** [comment]
Hi @Sophie-2e,

The specific issue has not been merged and released to the production version of Dokan just yet.

The good news is that you can expect to see the solution in version 3.9.1 of Dokan. We're actively working on it, and the release is on the horizon.

We appreciate your patience and understanding as we work to provide you with the best possible solution.

If you have any further questions or need more information, please feel free to reach out.

**Comment by Sophie-2e** [comment]
Ok thanks for the follow up. lLt's see if it is released and really fixed in the next coming weeks then, as for now Dokan admin users can not use this option without losing money, or not earning anything.

**Comment by Sophie-2e** [comment]
@Aunshon just updated Dokan to 3.9.1 + 3.9.2 and the issue has not been fixed. When will it be fixed? Your team is also blocking my post in your FB group to alert other Dokan users to get rid of the option until it is fixed so they don't lose money. Either you fix it, or you let know your consumer. Be fair. 

When will it be fixed?

**Comment by nurul-umbhiya** [comment]
@Sophie-2e Sorry you had to wait this long. We provided a fix last month but the PR is still under the QA team. I've set an **Urgent** label for this PR. Hopefully, within the next release, you'll get the fix.

**Comment by Sophie-2e** [comment]
@nurul-umbhiya thank you for the follow-up and for adding the urgent label 👌
