### ISSUE TITLE
STORE CARDS: on Top of Mega Menu + /br added compromising design

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2121]
### Bug Description

Since latest updates, there is design issue with the Store Card in the Followed Shops Tab in the Customer Account.

- [ ] Store Cards are displayed on top of the Elementor mega menu : video available in https://app.dokan.co/support/40259
- [x]  there is some /br which is added to the store card and compromise the design: video available in https://app.dokan.co/support/40260

Below is the CSS provided by Jahidul Hassan to fix these issues:

/* DOKAN - Customer Account > Favourite Shops > Fix Z-index for Store Cards on Top of Elementor Mega Menu */
#dokan-seller-listing-wrap.grid-view .store-content{
    z-index: 1 !important;
}
.store-footer{
    z-index: 2 !important;
}

/* DOKAN: Fix Design of Shop Cards on Customer Account Page in Favourite Shops tab */
.store-wrapper br {
display: none;
}

Please fix these piece of codes at the plugin level so no extra CSS is needed, as it used to be before the latest updates.

### Step To Reproduce

Since latest updates, there is design issue with the Store Card in the Followed Shops Tab in the Customer Account.

- [ ] Store Cards are displayed on top of the Elementor mega menu : video available in https://app.dokan.co/support/40259
- [x]  there is some /br which is added to the store card and compromise the design: video available in https://app.dokan.co/support/40260

### Expected Behaviour

That we don't need extra CSS to fix design issues of the Store Cards, so the codes should be as follow at the plugin level :

/* DOKAN - Customer Account > Favourite Shops > Fix Z-index for Store Cards on Top of Elementor Mega Menu */
#dokan-seller-listing-wrap.grid-view .store-content{
    z-index: 1 !important;
}
.store-footer{
    z-index: 2 !important;
}

/* DOKAN: Fix Design of Shop Cards on Customer Account Page in Favourite Shops tab */
.store-wrapper br {
display: none;
}

### Actual Behaviour

- [ ] Store Cards are displayed on top of the Elementor mega menu : video available in https://app.dokan.co/support/40259
- [ ]  there is some /br which is added to the store card and compromise the design: video available in https://app.dokan.co/support/40260

### Additional Information

Already contacted the customer support team which advised me to open this GitHub so your devs can fix it: 
- [ ] Store Cards are displayed on top of the Elementor mega menu : video available in https://app.dokan.co/support/40259
- [x]  there is some /br which is added to the store card and compromise the design: video available in https://app.dokan.co/support/40260

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.9.5]
2. Dokan Pro Version: [3.9.6]
3. WooCommerce Version: [8.4.0]
4. Browser [all]
5. Current Theme: [Store Front, Blocksy etc...]
```

**Comment by shohag121** [comment]
Hello @Sophie-2e,

I have checked with the support team about this issue. 
Found that the Elementor applies `z-index: 2147483640` Initially but for some reason it is being overridden as `z-index: 1`.

**Images:**

![Screenshot 2024-02-13 at 10 47 07 am](https://github.com/getdokan/dokan/assets/5476784/7acb0095-cfed-49c5-a886-5bcf5679c79e)
![Screenshot 2024-02-13 at 10 47 36 am](https://github.com/getdokan/dokan/assets/5476784/99741855-a645-4e7b-9748-57cb9475d840)

 
 `z-index: 1` is a deficient value for the mega menu here. If dokan sets its `z-index` values below 1, it might cause more CSS issues elsewhere.
 
 I highly suggest that you contact the Elementor support team so that they can bring a permanent solution to the issue.
 Please let us know in case if you need additional assistance from our end after contacting the Elementor Support team.
 
 In the meantime, I'll contact the Dokan support team so that they can provide you with a custom solution for now if your website needs any.

**Comment by Sophie-2e** [comment]
Hello @shohag121 @devAsadNur 

No this is not the issue as I already proved to your customer support team: https://share.vidyard.com/watch/cPYTRESD4qSPT3qZTrixCp?

And here is more proof and ivestigation: https://share.vidyard.com/watch/k9ozfbCwfZGNifDsU8xvYk?

Already contacted Elementor that will not do anything as the issue only occurs with this Dokan element, so they say Dokan needs to fix it at plugin level. And again, until last month,, it was working fine and I did not make any change to this section nor to the menu on the website. Waiting for your news.

**Comment by shohag121** [comment]
Hello @Sophie-2e,

Thanks for reporting the issue to us.
I've implemented the CSS changes in [this PR](https://github.com/getdokan/dokan/pull/2171).

Thanks again.

**Comment by Sophie-2e** [comment]
You are welcome @shohag121 , big thanks to you for fixing so many reported issues, you rock ! 👌 🙌 🫶

**Comment by Sophie-2e** [comment]
Hello @shohag121 , I managed to fix the <br> issue by using a proper Elementor Shortcode widget instead of an Elementor text widget for woocommerce my account shortcode. However, it does not fix the z-index issue:

- [ ] Store Cards are displayed on top of the Elementor mega menu : video available in https://app.dokan.co/support/40259

Just to let you know ;-)
