### ISSUE TITLE
DOKAN / STRIPE EXPRESS - Order Confirmation Page shows Pending Payment at first while payment succeed

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2236]
### Bug Description

Following on Dokan support ticket #56085

Another bug with Stripe Express that I reported a long time ago, which was fixed for a few months and which is back: Order Confirmation Page shows Pending Payment at first while payment succeeds, and customers need to reload the page to see the payment status change, or to visit their dashboard.

This needs to be fixed as many consumers will open support tickets just to confirm their payment has passed and the order is being processed.

### Step To Reproduce

use stripe express, pay an order, check order confirmation page status payment, see payment pending instead of processing

### Expected Behaviour

Have a the right order status without reloading the pagethe

### Actual Behaviour

Another bug with Stripe Express that I reported a long time ago, which was fixed for a few months and which is back: Order Confirmation Page shows Pending Payment at first while payment succeeds, and customers need to reload the page to see the payment status change, or to visit their dashboard.

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.10.2]
2. Dokan Pro Version: [3.10.2]
3. WooCommerce Version: [8.7.0]
4. Browser [all]
5. Current Theme: [all]
```

**Comment by mralaminahamed** [comment]
After investigating this further, we have determined that the issue has been resolved by the WooCommerce team. No changes are required on our end. We will be closing this issue. Thank you for taking the time to report it initially.

**Comment by Sophie-2e** [comment]
Hello @mralaminahamed, indeed, forgot to add my note about this here too: issue was caused by Woo, fix since updated to Woo 8.8.2 fixed 😉 I will go ahead and close this Github

**Comment by Sophie-2e** [comment]
@mralaminahamed @mrabbani issue is back since Dokan 3.11.3 and Dokan Pro 3.11.2 Please fix it again.

**Comment by Sophie-2e** [comment]
@mralaminahamed @mrabbani FYI issue still there in Dokan 3.11.4 + Pro 3.11.3

**Comment by Sophie-2e** [comment]
@mralaminahamed @mrabbani FYI Fixed with Dokan 3.10.5+ Pro 3.10.4

**Comment by dan504301** [comment]
@mralaminahamed @Sophie-2e , I encountered a similar issue today.

The payment was completed in Stripe, but the order remained in a pending state in WooCommerce.

Then, the client attempted the payment again, and the order status changed to processing.

As a result, there was a duplicate payment with the same order number. This is the first time I've seen this happen in two years.

I didn't see any errors whatsoever.
