### ISSUE TITLE
Inconsistent Product Sorting by Price on Shop Page for Vendor-Added Products

### ISSUE THREAD

**Issue by sazz-pranto** [getdokan/dokan#2431]
### Bug Description

When products are added from the Admin Panel, they can be sorted by price (from high to low and vice versa) correctly on the Shop Page. However, products added from the Vendor Dashboard do not sort correctly by price on the Shop Page. For a better understanding, please have a look at this video: https://d.pr/v/RGgZzy

### Step To Reproduce

1. From the Vendor Dashboard, add several products with varying prices.
2. Go to the Shop Page and attempt to sort the products by price (high to low or low to high).
3. Observe the sorting behavior.

### Expected Behaviour

Products added from the Vendor Dashboard should be sorted by price accurately on the Shop page, just as they are for products added through the Admin Panel.

### Actual Behaviour

As shown in the video. 

### Additional Information

**System Status:**

Dokan: v3.13.0
WooCommerce: v9.3.3
WordPress: v6.6.2

### Environment (please complete the following information)

```shell
1. Dokan Version: [e.g. v3.1.2]
2. Dokan Pro Version: [e.g. v3.1.2]
3. WooCommerce Version: [e.g. v4.9.2]
4. Browser [e.g. chrome, safari]
5. Current Theme: [e.g. Store Front]
```

**Comment by mrabbani** [comment]
@sazz-pranto vai, It is addressed in https://github.com/getdokan/dokan/pull/2098

**Comment by TanvirHasan19** [comment]
@jamil-mahmud bhai || @mrabbani bhai || @kzamanbd bhai,

The issue still persists in the latest version of the Dokan Lite plugin. I kindly request that you investigate this matter and implement a proper solution as soon as possible to address the incompatibility between Dokan and WooCommerce's default product sorting options.

We've already received a couple of reports from clients experiencing this issue. Your prompt attention to this matter would be greatly appreciated.

Thanks in advance!

**Comment by TanvirHasan19** [comment]
@jamil-mahmud Bhai || @kzamanbd Bhai,

I've created a snippet that temporarily resolves the issue. You can find the snippet at the following link: https://gist.github.com/TanvirHasan19/91dd4362d19072337ca9b02796e5ef07

**Comment by kzamanbd** [comment]
@TanvirHasan19 bhai, Thanks for implementing the temporary solution — really appreciate your quick action!

We have already implemented a more permanent fix in this PR: https://github.com/getdokan/dokan/pull/2098. A big thanks to @devAsadNur bhai for creating this PR, and also to you for handling the temporary solution so efficiently. There are a few technical dependencies we are currently working through, and once resolved, we’ll release it soon.
